import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Profile from '../components/Profile'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-[rgb(22,27,34)] text-white'>
      <Head>
        <title>Connors portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
     <Header />

     {/*Profile*/}
     <section id='Profile'>
      <Profile />
     </section>

     {/* About */}
     <section id='About '>

     </section>

     {/* Experience */}

     {/* Skills */}

     {/* Projects */}

     {/* Contact me */}
    </div>
  )
}
